### PR TITLE
bat

### PR DESCRIPTION
**Pull request by animationzl**
bosh acceptance tests

### CODE REVIEW

**Comment by liusheng** [comment]
recheck

**Comment by liusheng** [comment]
recheck

**Comment by liusheng** [comment]
recheck

**Comment by liusheng** [comment]
recheck

**Comment by liusheng** [comment]
recheck

**Comment by liusheng** [comment]
recheck

**Comment by liusheng** [comment]
recheck

**Comment by liusheng** [comment]
recheck

**Comment by liusheng** [comment]
recheck

**Comment by liusheng** [comment]
recheck

**Comment by liusheng** [comment]
recheck

**Comment by animationzl** [comment]
recheck

**Comment by liusheng** [comment]
recheck

**Comment by liusheng** [comment]
recheck

**Comment by liusheng** [comment]
recheck

**Comment by liusheng** [comment]
recheck

**Comment by liusheng** [comment]
recheck

**Comment by liusheng** [comment]
recheck

**Comment by liusheng** [comment]
recheck

**Comment by liusheng** [comment]
recheck

**Comment by liusheng** [comment]
recheck

**Comment by liusheng** [comment]
recheck

**Comment by liusheng** [comment]
recheck

**Comment by liusheng** [comment]
recheck

**Comment by liusheng** [comment]
recheck

**Comment by liusheng** [comment]
recheck

**Comment by liusheng** [comment]
recheck

**Comment by liusheng** [comment]
recheck

**Comment by liusheng** [comment]
recheck

**Pull request closed without merging**
